### ISSUE TITLE
go artifact not available through maven central?

### ISSUE THREAD

**Issue by virtuald** [gocd/sample-plugins#5]
README says "Sample plugins use maven for dependency resolution. The Go plugin API jar is now available through Maven central.". But, that doesn't really seem to be the case...

```
Downloading: https://repo.maven.apache.org/maven2/com/thoughtworks/go/go-plugin-api/15.3.0/go-plugin-api-15.3.0.pom
[WARNING] The POM for com.thoughtworks.go:go-plugin-api:jar:15.3.0 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/thoughtworks/go/go-plugin-api/15.3.0/go-plugin-api-15.3.0.jar

...

[ERROR] Failed to execute goal on project curl-plugin: Could not resolve dependencies for project com.thoughtworks.go:curl-plugin:jar:15.3.0: Could not find artifact com.thoughtworks.go:go-plugin-api:jar:15.3.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Looking at search.maven.org, there does not appear to be any thoughtworks go artifacts published to maven.

**Comment by arvindsv** [comment]
I think the group ID is wrong. It is on Maven central, and should be continuously updated from build.go.cd, directly. Can you take a look at [this](http://search.maven.org/#search%7Cga%7C1%7Cgo-plugin-api)?

**Comment by virtuald** [comment]
Those appear to be the right artifacts... seems like the pom needs to be updated then.

**Comment by CzarScar** [comment]
I also found this on 17.2. And I have created a pull request. But not accepted.

**Comment by arvindsv** [comment]
@CzarScar [The PR](https://github.com/gocd/sample-plugins/pull/6) was not merged due to a pending CLA (Contributor License Agreement) check. The bot was supposed to add a message to the PR, but doesn't seem to have done that. If you sign the CLA at https://cla.gocd.org/gocd/sample-plugins?pullRequest=6 and let me know, here or on the PR, I can merge it. Would be nice to have it be updated to the 18.x series too, of course.

**Comment by arvindsv** [comment]
Also, the real skeleton plugins for each type is available along with the documentation for that plugin type. For instance: See the first few sentences in https://plugin-api.gocd.org/current/notifications/ for a link to: https://github.com/gocd-contrib/notification-skeleton-plugin

I'd use those instead of this repo.

**Comment by CzarScar** [comment]
OK, I am not sure if we can leave the version blank and make maven to find from the maven central repo for the latest version? If so, all the contributors and users will not meet this issue again. I will have try about this.

**Comment by arvindsv** [comment]
Ok, I'll wait.

**Comment by gzliuqingyun** [comment]
Same error.
Change the `groupId` field from `com.thoughtworks.go` to `cd.go.plugin` in the `pom.xml` file, fixed the problem.
